version: '3'
services:
  docker_mysql:
    container_name: mysql
    build: ./mysql/
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/db:/var/lib/mysql/
  
  rabbitmq:
    container_name: rabbitmq
    tty: true
    image: rabbitmq:3.8-management-alpine
    ports: 
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
  
  judge_server:
    container_name: judge_server
    build: ./judge/
    image: judge_server
    restart: always
    tty: true
    depends_on: 
      - docker_mysql
      - rabbitmq
    volumes:
      - ./judge:/code/
  app:
    container_name: app
    build: .
    image: flask_with_postgres
    depends_on:
      - docker_mysql
    ports:
      - 5000:5000
    volumes: 
      - ./app:/code/app
    stdin_open: true
    environment:
      ENV_CONFIG: docker
      SQLALCHEMY_POOL_SIZE: 5
      SQLALCHEMY_MAX_OVERFLOW: 10
      SQLALCHEMY_POOL_TIMEOUT: 30